import {factorial} from './Factorial';
const add=require('./addition')
const subtract=require('./substraction')
const areaofcircle=require('./Area-of-circle')
const areaofcylinder=require('./Area-of-cylinder')
const areaofrectangle=require('./Area-of-rectangle')
const comparsion=require('./Comparsion-number')
const currentDate=require('./Current-date')
const areaofsquare=require('./Area-of-square')
const areaoftraingle=require('./Area-of-traingle')
const factorial=require('./Factorial')
const multiplication=require('./multiplication-PI')
const comparsionString=require('./String-comparsion')
const reversestring=require('./String-reverse')
const diwaliwhen=require('./Diwali-when')
const millisecondsconvertor=require('./Milliseconds-to-sec-min-hrs-days,yrs-')
const check=require('./node_modules/testing-lib/test')
console.log(check(add([9,9,-3,8.9]),23.9))
console.log(check(subtract(5,6),1))
console.log(check(areaofcircle(5),78.53981633974483))
console.log(check(areaofcylinder(4,5),226.1946710584651))
console.log(check(areaofrectangle(5,6),30))
console.log(check(comparsion(2,6),'a is smaller'))
console.log(check(currentDate(),'2020-06-11T11:27:08.727Z'))
console.log(check(areaofsquare(5),25))
console.log(check(areaoftraingle(3,6),9))
console.log(check(factorial(6),720))
console.log(check(multiplication(5),15.707963267948966))
console.log(check(comparsionString('abc'),'ping pong! beep boop'))
console.log(check(reversestring('JavaScript'),'tpircSavaJ'))
console.log(check(diwaliwhen(14,11),156))
console.log(check(millisecondsconvertor(1),''))