const add=require('./addition')
const subtract=require('./substraction')
const areaofcircle=require('./Area-of-circle')
const areaofcylinder=require('./Area-of-cylinder')
const areaofrectangle=require('./Area-of-rectangle')
const comparsion=require('./Comparsion-number')
const currentDate=require('./Current-date')
const areaofsquare=require('./Area-of-square')
const areaoftraingle=require('./Area-of-traingle')
const factorial=require('./Factorial')
const multiplication=require('./multiplication-PI')
const comparsionString=require('./String-comparsion')
const reversestring=require('./String-reverse')
const diwaliwhen=require('./Diwali-when')
const millisecondsconvertor=require('./Milliseconds-to-sec-min-hrs-days,yrs-')
console.log(add([9,9,-3,8.9]))
console.log(subtract(5,6))
console.log(areaofcircle(5))
console.log(areaofcylinder(4,5))
console.log(areaofrectangle(5,6))
console.log(comparsion(2,6))
console.log(currentDate())
console.log(areaofsquare(5))
console.log(areaoftraingle(3,6))
console.log(factorial(6))
console.log(multiplication(5))
console.log(comparsionString('abc'))
console.log(reversestring('JavaScript'))
console.log(diwaliwhen(14,11))
console.log(millisecondsconvertor(1))